#!/bin/sh
# ============================================================
# MCHR-BL CLI (HeroRBL) — Debian / Ubuntu / VPS Installer
# Ditujukan untuk VPS Debian 11/12 (juga jalan di Ubuntu/Mint)
#
# Cara pakai:
#   bash <(curl -s https://raw.githubusercontent.com/GegeDevs/mchrbl-cli/refs/heads/main/install-debian.sh)
# atau download & jalankan langsung.
#
# Hasil install:
#   ~/mchrbl-cli/herorbl.py   -> script utama
#   ~/mchrbl-cli/locales/     -> language pack (id/en)
#   ~/.local/bin/ubl-go       -> launcher (python3 herorbl.py)
# ============================================================

set -e

REPO_URL="https://raw.githubusercontent.com/GegeDevs/mchrbl-cli/refs/heads/main"
INSTALL_DIR="${HERORBL_DIR:-$HOME/mchrbl-cli}"
BIN_DIR="$HOME/.local/bin"

echo "[Info.] Memulai instalasi MCHR-BL CLI (Debian/VPS)..."
echo "[Info.] Direktori install: $INSTALL_DIR"

# Helper download: coba wget dulu, fallback curl, gagal total = exit
download() {
    url="$1"; dest="$2"
    if command -v wget >/dev/null 2>&1; then
        wget -q -O "$dest" "$url" && return 0
    fi
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL -o "$dest" "$url" && return 0
    fi
    echo "[Error.] Gagal mengunduh: $url (butuh wget atau curl)"
    exit 1
}

# 1. Pastikan python3 terinstall
if ! command -v python3 >/dev/null 2>&1; then
    echo "[Info.] python3 tidak ditemukan, menginstall..."
    if [ "$(id -u)" -eq 0 ]; then
        apt-get update -y
        apt-get install -y python3
    elif command -v sudo >/dev/null 2>&1; then
        sudo apt-get update -y
        sudo apt-get install -y python3
    else
        echo "[Error.] python3 tidak ada dan tidak ada sudo. Install manual: apt install python3"
        exit 1
    fi
fi

# 2. Buat direktori
mkdir -p "$INSTALL_DIR" "$BIN_DIR" "$INSTALL_DIR/locales"

# 3. Unduh script + language pack
echo "[Info.] Mengunduh herorbl.py..."
download "$REPO_URL/herorbl.py" "$INSTALL_DIR/herorbl.py"

echo "[Info.] Mengunduh language pack (id/en)..."
download "$REPO_URL/locales/id.json" "$INSTALL_DIR/locales/id.json"
download "$REPO_URL/locales/en.json" "$INSTALL_DIR/locales/en.json"

# 4. Buat launcher ubl-go
cat > "$BIN_DIR/ubl-go" <<EOF
#!/bin/sh
# Launcher MCHR-BL CLI — generated by install-debian.sh
exec python3 "$INSTALL_DIR/herorbl.py" "\$@"
EOF
chmod +x "$BIN_DIR/ubl-go"
echo "[Success.] Launcher dibuat: $BIN_DIR/ubl-go"

# 5. Pastikan $BIN_DIR masuk PATH di shell berikutnya
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
    rc_found=""
    for rc in "$HOME/.profile" "$HOME/.bashrc"; do
        if [ -f "$rc" ]; then
            rc_found="$rc"
            grep -qxF "export PATH=\"$BIN_DIR:\$PATH\"" "$rc" || \
                echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$rc"
        fi
    done
    # User baru tanpa rc file sama sekali -> buatkan .profile
    if [ -z "$rc_found" ]; then
        echo "export PATH=\"$BIN_DIR:\$PATH\"" > "$HOME/.profile"
    fi
    echo "[Info.] PATH ditambahkan ke ~/.profile / ~/.bashrc"
fi

echo ""
echo "=============================================="
echo " [Success.] Instalasi selesai!"
echo "   Script  : $INSTALL_DIR/herorbl.py"
echo "   Launcher: $BIN_DIR/ubl-go"
echo "=============================================="
echo ""
echo " Jalankan:"
echo "   ubl-go        (buka shell baru / source ~/.bashrc dulu)"
echo ""
echo " Tips VPS:"
echo "  1. Jalankan lewat tmux/screen biar aman dari putus SSH:"
echo "     tmux new -s ubl && ubl-go"
echo "  2. Set zona waktu biar hitungan jam war akurat:"
echo "     sudo timedatectl set-timezone Asia/Jakarta"
echo "  3. Waktu war: 22:55 WIB / 23:55 WITA / 00:55 WIT (besok)."
echo ""
